# Generated by Django 3.1 on 2020-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regemp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemod',
            name='user',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
