# Generated by Django 3.1 on 2020-10-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Regemp', '0002_profilemod_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemod',
            name='user',
        ),
    ]
